### ISSUE TITLE
Landscape review?

### ISSUE THREAD

**Issue by matthew-brett** [matthew-brett/czi-nibabel#12]
@effigies - would you mind taking a look at my rewrite of the landscape section?

**Comment by effigies** [comment]
Looks good. I can submit a PR around noon EDT, but a couple quick comments:

1) FreeSurfer has had public version control (and accepted patches) since 2017: https://github.com/freesurfer/freesurfer/. CI is build only, no tests.
2) AFNI only has one component that uses nibabel, which is the defunct MEICA (split into other projects, independent of AFNI). We could just drop this mention, if it turns out not to be relevant.
3) AFNI does do some tests, though I don't think they submit coverage reports: https://app.circleci.com/pipelines/github/afni/afni/1890/workflows/ede546e6-8fa2-4246-9da7-ce3f95f867b3/jobs/4510

**Comment by matthew-brett** [comment]
Thanks - that's useful.  I've put that into the doc in d1770c8.   Do you know when AFNI started running tests?

**Comment by effigies** [comment]
2018 according to one developer I just pinged. Though apparently Yarik helped them set up Travis a while before that.

**Comment by matthew-brett** [comment]
I found some very very basic tests in Yarik's original travis-ci setup - https://github.com/afni/afni/pull/36/files - so I gave them the benefit of the 2 years doubt...

**Comment by oesteban** [comment]
Just submitted #14 with three objectives:

- more cohesive presentation of alternatives (also replaced the term "competitors")
- mention and give relevance to Nipype as a great companion of Nibabel
- illustrate that now people are easily building high-level pipelines with great success (perhaps we should connect this to the fact that the high-level is now well covered and it would be great that someone takes on the need for education about the low-level stuff)

**Comment by oesteban** [comment]
I think we can close this general one and address maybe particular problems after merging #14? Feel free to reopen if you don't agree 👍
